use strict;
use warnings;

use JSON ();
use LWP::UserAgent;

use Data::Dumper;

use constant URL_SERPS_DEFAULT =>
  "http://sourceforge.jp/projects/cres/svn/view/qthoney/qth_toolbar/qth_search_list.json?view=co";

my ($url) = (@ARGV, URL_SERPS_DEFAULT);

warn "* downloading search list file. url: $url\n";
my $ua = LWP::UserAgent->new();
my $response = $ua->get($url);
$response->is_success() or
  die "- getting file failed. http status: ".$response->status_line."\n";
warn "- done.\n";

warn "* decoding file content as json\n";
my $serps;
eval{
    $serps = JSON::decode_json($response->content());
};
$@ and die "- decoding json failed. $@\n";
warn "- done.\n";

my $serps_url = [];
foreach(@$serps){
    push(@$serps_url, $_->{base_url});
}

{
    local $Data::Dumper::Terse = 1;
    local $Data::Dumper::Indent = 1;
    $serps = Dumper($serps);
    $serps_url = Dumper($serps_url);
    my $today = `date '+%F %T %Z'`;
    chomp($today);

    print <<CODE_SERPS_PL;
# this file was generated by get_serps.pl
# original search list file is got from: $url
# generated date: $today

package serps;

use strict;
use warnings;

use Exporter qw/import/;
our \@EXPORT_OK = qw/\$serps \$serps_url/;

our \$serps = $serps;
our \$serps_url = $serps_url;
1;
CODE_SERPS_PL
}
