# this file was generated by get_serps.pl
# original search list file is got from: http://sourceforge.jp/projects/cres/svn/view/qthoney/qth_toolbar/qth_search_list.json?view=co
# generated date: 2013-02-14 16:39:46 JST

package serps;

use strict;
use warnings;

use Exporter qw/import/;
our @EXPORT_OK = qw/$serps/;

our $serps = [
  {
    'keyword_index' => 1,
    'search_label' => 'MEW',
    'base_url' => '^http://mew\.ntcir\.nii\.ac\.jp/.+#q=(.+)', # manually modified
    'keyword_type' => 'in_url',
  },
  {
    'search_label' => 'google-image',
#    'base_url' => 'http://images.google.com/images',
   'base_url' => '^http://www\.google\.co\.jp/search\?.*tbm=isch', # manually modified
    'keyword_type' => 'parameter',
    'index_key' => 'start',
    'keyword_key' => 'q',
   observe_keys => [qw/q/], # manually modified
  },
  {
    'search_label' => 'google-jp',
    'base_url' => '^http://www\.google\.co\.jp/search', # manually modified
    'keyword_type' => 'parameter',
    'index_key' => 'start',
    'keyword_key' => 'q',
   observe_keys => [qw/q num/], # manually modified
   preference_url => '^http://www.google.co.jp/setprefs$', # manually modified
  },
  {
    'search_label' => 'google-web',
    'base_url' => '^http://www\.google\.com/search', # manually modified
    'keyword_type' => 'parameter',
    'index_key' => 'start',
    'keyword_key' => 'q',
   observe_keys => [qw/q num/], # manually modified
  },
  {
    'keyword_index' => 1,
    'search_label' => 'kakaku.com',
    'base_url' => '^http://kakaku\.com/search_results/([^/]+)/', # manually modified
    'keyword_type' => 'in_url',
    'index_key' => 'page',
   observe_keys => [qw/category nkey n sort/],
  },
  {
    'keyword_index' => 1,
    'search_label' => 'alc',
#    'base_url' => '^http://eow\.alc\.co\.jp/([^/]+)/UTF-8/',
    'base_url' => '^http://eow\.alc\.co\.jp/search\?q=([^/]+)', # manually modified
    'keyword_type' => 'in_url',
    'index_key' => 'pg',
   observe_keys => [qw/q/],
  },
  {
    'search_label' => 'yahoo',
    'base_url' => '^http://search\.yahoo\.co\.jp/search', # manually modified
    'keyword_type' => 'parameter',
    'index_key' => 'b',
    'keyword_key' => 'p',
   observe_keys => [qw/p/],
   preference_url => '^http://wrs.search.yahoo.co.jp/.+/savepref$', # manually modified
  },
# out of service
#  {
#    'keyword_index' => 1,
#    'search_label' => 'goo-mix',
#    'base_url' => '^http://mix\.search\.goo\.ne\.jp/#web,oshiete/([^/]+)', # manually modified
#    'keyword_type' => 'in_url',
#    'index_key' => ''
#  },
  {
    'search_label' => 'goo',
    'base_url' => '^http://search\.goo\.ne\.jp/web.jsp', # manually modified
    'keyword_type' => 'parameter',
    'index_key' => 'FR',
    'keyword_key' => 'MT',
   observe_keys => [qw/MT/],
  },
  {
    'search_label' => 'bing',
    'base_url' => '^http://www\.bing\.com/search', # manually modified
    'keyword_type' => 'parameter',
    'index_key' => 'first',
    'keyword_key' => 'q',
   observe_keys => [qw/q lf/],
   preference_url => '^http://www.bing.com/account/web$', # manually modified
  }
];
1;
